### ISSUE TITLE
无法运行起来

### ISSUE THREAD

**Issue by hlj2722** [huaibaobao2017/Weex#1]
npm start 之后报以下错误

(Emitted value instead of an instance of Error) <p-list v-for="tab in tabTitles">: component lists rendered with v-for should have explicit keys. See https://vuejs.org/guide/list.html#key for more info.

 @ ./src/Categories.vue 10:2-196
 @ ./.temp/Categories.js?entry=true
 @ multi (webpack)-dev-server/client?http://192.168.31.252:8081 ./.temp/Categories.js?entry=true

 warning  in ./src/Strict.vue

(Emitted value instead of an instance of Error) <p-list v-for="tab in tabTitles">: component lists rendered with v-for should have explicit keys. See https://vuejs.org/guide/list.html#key for more info.

 @ ./src/Strict.vue 10:2-192
 @ ./.temp/Strict.js?entry=true
 @ multi (webpack)-dev-server/client?http://192.168.31.252:8081 ./.temp/Strict.js?entry=true

**Comment by huaibaobao2017** [comment]
您好，这不是开源项目。有写依赖没有上传导致无法运行。
